GET http://localhost:3333/track/?url=http%3A%2F%2Flocalhost%3A3333%2F&date=25-07-2020 HTTP/1.1

###

POST http://localhost:3333/track
content-type: text/plain;charset=UTF-8

v=1
    &ds=web
    &aip=1
    &tid=UA-135954444-1
    &cid=0.3k08ja7qn0t
    &t=pageview&sd=24-bits
    &dt=Finding%20Nora
    &dl=https%3A%2F%2Flocalhost%3A3333%2F
    &ul=nl
    &de=UTF-8
    &sr=1440x900

###

POST http://localhost:3333/
content-type: text/plain;charset=UTF-8

v=1
    &ds=web
    &aip=1
    &tid=UA-135954444-1
    &cid=0.3k08ja7qn0t&t=pageview
    &sd=24-bits
    &dt=Finding%20Nora
    &dl=https://finding-nora.com
    &ul=nl
    &de=UTF-8
    &sr=1440x900

